import numpy as np
x = np.random.randint(0,3,6)
print("1st array:")
print(x)
y = np.random.randint(0,3,6)
print("2nd array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)
